
const reference = {
  // General Reference Parameters
  general: [
    { param: "Ferritin ⭐", unit: "ng/ml", women: "premenopausal: 15–150\npostmenopausal: 15–300\noptimal: 70–200", men: "30–400\noptimal: 100–300", comment: "Iron storage protein", explanation: "Iron storage protein; reflects total body iron stores. Low levels indicate iron deficiency before anemia develops. High levels may indicate inflammation, infection, or iron overload conditions." },
    { param: "TSH ⭐", unit: "mIU/l", women: "0.5–2.5 (optimal)", men: "0.5–2.5 (optimal)", comment: "Thyroid stimulating hormone", explanation: "Main regulator of thyroid function. Elevated levels suggest hypothyroidism (underactive thyroid); low levels suggest hyperthyroidism (overactive thyroid)." },
    { param: "Vitamin D (25-OH) ⭐", unit: "ng/ml", women: "50–70 (optimal)", men: "50–70 (optimal)", comment: "Vitamin D status", explanation: "Essential for calcium absorption, bone health, immune function, and gene expression. Influences over 2000 genes and has receptor sites in nearly every cell. Deficiency linked to numerous chronic diseases." },
    { param: "Vitamin B12 ⭐", unit: "pg/ml", women: ">600 (optimal 1000)", men: ">600 (optimal 1000)", comment: "Vitamin B12 status", explanation: "Critical for nerve function, DNA synthesis, and red blood cell formation. Functional deficiency can occur even with \"normal\" levels; active B12 (holotranscobalamin) is more accurate." },
    { param: "Holo-transcobalamin", unit: "pmol/l", women: ">100", men: ">100", comment: "Active B12", explanation: "Active form of B12 that can be utilized by cells. More accurate indicator of B12 status than total B12. Essential for methylation processes and neurological health." },
    { param: "Folate (RBC) ⭐", unit: "ng/ml", women: ">16", men: ">16", comment: "Folate status", explanation: "Crucial for DNA synthesis, repair, and methylation. Works synergistically with B12. Important for cardiovascular health through homocysteine regulation." },
    { param: "Zinc ⭐", unit: "mg/l", women: "6–7", men: "6–7", comment: "Zinc status", explanation: "Essential for immune function, protein synthesis, wound healing, DNA synthesis, and cell division. Cofactor for over 300 enzymes. Serum levels may not reflect tissue status." },
    { param: "Magnesium (whole blood) ⭐", unit: "mmol/l", women: "0.85–1.0", men: "0.85–1.0", comment: "Magnesium status", explanation: "Required for over 600 enzymatic reactions. Critical for energy production, muscle function, nerve transmission, and bone formation. Serum levels represent only 1% of body magnesium." },
    { param: "Selenium ⭐", unit: "µg/l", women: "140–160", men: "140–160", comment: "Selenium status", explanation: "Antioxidant mineral essential for thyroid hormone metabolism, immune function, and fertility. Component of glutathione peroxidase enzymes that protect against oxidative damage." },
    { param: "Omega-3 Index ⭐", unit: "%", women: ">8", men: ">8", comment: "Omega-3 status", explanation: "Measures EPA and DHA in red blood cell membranes. Reflects long-term omega-3 status. Higher levels associated with reduced cardiovascular risk, improved cognitive function, and reduced inflammation." },
    { param: "Total protein", unit: "g/dl", women: ">7.0 (optimal 7.3–7.6)", men: ">7.0 (optimal 7.3–7.6)", comment: "Overall protein status", explanation: "Sum of all proteins in blood, primarily albumin and globulins. Indicator of nutritional status, liver function, and hydration. Low levels may indicate malnutrition or protein-losing conditions." }
  ],

  // Amino Acids Reference Parameters
  amino: [
    { param: "Leucine", unit: "µmol/L", women: "110–217 (Target: upper half)", men: "110–217 (Target: upper half)", comment: "BCAA, essential for muscle protein synthesis", explanation: "Critical for muscle protein synthesis and energy production during exercise. Directly activates mTOR pathway for muscle growth and recovery." },
    { param: "Isoleucine", unit: "µmol/L", women: "58–117 (Target: upper half)", men: "58–117 (Target: upper half)", comment: "BCAA, supports glucose uptake in muscle", explanation: "Supports glucose uptake in muscle, wound healing, and immune function. Important for hemoglobin formation and energy regulation." },
    { param: "Valine", unit: "µmol/L", women: "206–317 (Target: upper half)", men: "206–317 (Target: upper half)", comment: "BCAA, supports nitrogen balance and immune system", explanation: "Supports nitrogen balance, muscle metabolism, and cognitive function. Important for immune system function and tissue repair." },
    { param: "Methionine", unit: "µmol/L", women: "25–40 (Target: upper half)", men: "25–40 (Target: upper half)", comment: "Sulfur-containing amino acid for methylation processes", explanation: "Sulfur-containing amino acid critical for methylation processes, detoxification, and antioxidant production. Precursor to cysteine and glutathione." },
    { param: "Lysine", unit: "µmol/L", women: "139–240 (Target: upper half)", men: "139–240 (Target: upper half)", comment: "Required for collagen formation, immune function", explanation: "Required for collagen formation, calcium absorption, and protein synthesis. Supports immune function and may help manage herpes virus infections." },
    { param: "Phenylalanine", unit: "µmol/L", women: "51–109 (Target: upper half)", men: "51–109 (Target: upper half)", comment: "Precursor to tyrosine, dopamine, other neurotransmitters", explanation: "Precursor to tyrosine, dopamine, norepinephrine, and epinephrine. Important for cognitive function and mood regulation." },
    { param: "Tryptophan", unit: "µmol/L", women: "36–125 (Target: upper half)", men: "36–125 (Target: upper half)", comment: "Precursor to serotonin and melatonin, mood regulation", explanation: "Precursor to serotonin and melatonin. Critical for mood regulation, sleep quality, and stress resilience." },
    { param: "Threonine", unit: "µmol/L", women: "118–210 (Target: upper half)", men: "118–210 (Target: upper half)", comment: "Important for collagen, elastin, and antibody production", explanation: "Important for collagen, elastin, and antibody production. Supports gut mucosal integrity and immune function." },
    { param: "Histidine", unit: "µmol/L", women: "60–110 (Target: upper half)", men: "60–110 (Target: upper half)", comment: "Component of hemoglobin, myelin sheath maintenance", explanation: "Component of hemoglobin. Important for myelin sheath maintenance and histamine production." },
    { param: "Arginine", unit: "µmol/L", women: "110–180 (Target: upper half)", men: "110–180 (Target: upper half)", comment: "Precursor to nitric oxide, improves vascular function", explanation: "Precursor to nitric oxide, improving vascular function and blood flow. Supports wound healing and immune function." },
    { param: "Glutamine", unit: "µmol/L", women: "500–900 (Target: upper half)", men: "500–900 (Target: upper half)", comment: "Primary fuel for gut and immune cells", explanation: "Most abundant amino acid in blood. Primary fuel for intestinal cells and immune cells." }
  ],

  // Special Vitamins Reference Parameters
  vitamins: [
    { param: "Vitamin A (Retinol)", unit: "µg/L", women: "700–900 (optimal: 800)", men: "700–900 (optimal: 800)", comment: "Essential for vision, immune function, cellular differentiation", explanation: "Fat-soluble vitamin essential for vision, immune function, cellular differentiation, and gene expression. Works as antioxidant and supports epithelial tissue integrity." },
    { param: "Vitamin B1 (Thiamine, active)", unit: "µg/L", women: "39.8–60 (Target: 60)", men: "39.8–60 (Target: 60)", comment: "Important for carbohydrate metabolism and nerve function", explanation: "Water-soluble vitamin critical for carbohydrate metabolism and energy production. Essential for nerve function, heart health, and glucose metabolism." },
    { param: "Vitamin B2 (Riboflavin, active)", unit: "µg/L", women: "85–300 (Target: 250)", men: "85–300 (Target: 250)", comment: "Involved in energy production and antioxidant function", explanation: "Water-soluble vitamin involved in energy production, cellular growth, and antioxidant function. Cofactor for numerous redox reactions." },
    { param: "Vitamin B6 (P5P, active)", unit: "µg/L", women: "10.1–36 (Target: 36)", men: "10.1–36 (Target: 36)", comment: "Essential for amino acid metabolism and neurotransmitter synthesis", explanation: "Water-soluble vitamin involved in over 100 enzyme reactions. Active form (P5P) essential for amino acid metabolism, neurotransmitter synthesis, and homocysteine regulation." },
    { param: "Vitamin B9 (Folate, active)", unit: "µg/L", women: "100–270 (Target: 160)", men: "100–270 (Target: 160)", comment: "Important for DNA synthesis, repair, and methylation", explanation: "Water-soluble vitamin critical for DNA synthesis, repair, and methylation. Active form (5-MTHF) more effective than synthetic folic acid." },
    { param: "Vitamin B12 (active, Holo-TC)", unit: "pmol/L", women: ">100 (Target: 100–150)", men: ">100 (Target: 100–150)", comment: "Essential for nerve function, DNA synthesis, and methylation", explanation: "Water-soluble vitamin essential for nerve function, DNA synthesis, and red blood cell formation. Active form (holotranscobalamin) represents bioavailable B12." },
    { param: "Vitamin C", unit: "mg/L", women: "10–20 (Target: 10–20, up to 100 possible)", men: "10–20 (Target: 10–20, up to 100 possible)", comment: "Strong antioxidant, essential for collagen synthesis", explanation: "Water-soluble vitamin and powerful antioxidant. Essential for collagen synthesis, immune function, and neurotransmitter production. Regenerates other antioxidants." },
    { param: "Vitamin E", unit: "mg/L", women: "16–25 (Target: 16–25)", men: "16–25 (Target: 16–25)", comment: "Protects cell membranes from oxidative damage", explanation: "Fat-soluble antioxidant that protects cell membranes from oxidative damage. Eight different forms with varying biological activities." },
    { param: "Vitamin K2 (MK-7)", unit: "ng/L", women: "1000–6000 (Target: >1000)", men: "1000–6000 (Target: >1000)", comment: "Essential for calcium regulation and cardiovascular health", explanation: "Fat-soluble vitamin essential for calcium regulation. Directs calcium to bones and away from soft tissues. MK-7 form has longer half-life and greater bioactivity than MK-4." }
  ],

  // Inflammation Markers Reference Parameters
  inflammation: [
    { param: "CRP (C-reactive protein, hsCRP)", unit: "mg/L", women: "<1.0 (optimal: <0.8)", men: "<1.0 (optimal: <0.8)", comment: "Sensitive marker for systemic inflammation", explanation: "Sensitive marker of systemic inflammation produced by the liver. Elevated in infection, tissue damage, and chronic inflammation." },
    { param: "BDNF (Brain-derived neurotrophic factor)", unit: "ng/ml", women: "30–40 (Target)", men: "30–40 (Target)", comment: "Protein supporting neuronal growth and neuroplasticity", explanation: "Protein that supports survival and growth of neurons. Important for neuroplasticity, learning, and memory. Levels influenced by exercise, stress, sleep quality, and inflammation." },
    { param: "AGEs (Advanced glycation endproducts)", unit: "µg/ml", women: "<50 (lower is better)", men: "<50 (lower is better)", comment: "Compounds associated with aging and tissue damage", explanation: "Compounds formed when sugars react with proteins or lipids without enzyme control. Contribute to aging, inflammation, and tissue damage." },
    { param: "Nitrotyrosine", unit: "nmol/L", women: "<200 (Target)", men: "<200 (Target)", comment: "Marker for protein oxidation and nitrosative stress", explanation: "Marker of protein oxidation and nitrosative stress. Forms when peroxynitrite modifies tyrosine residues in proteins. Elevated in chronic inflammation." },
    { param: "Zonulin (Leaky gut marker)", unit: "ng/ml", women: "<30 (lower is better)", men: "<30 (lower is better)", comment: "Indicates intestinal permeability", explanation: "Protein that regulates tight junctions between intestinal cells. Elevated levels indicate increased intestinal permeability (\"leaky gut\")." }
  ],
  
  // Hematology Reference Parameters
  hematology: [
    { param: "Hemoglobin ✓ ⭐", unit: "g/dL", women: "12.0-15.5", men: "13.5-17.5", comment: "Oxygen-carrying protein in red blood cells", explanation: "Protein in red blood cells that carries oxygen from lungs to tissues. Low levels indicate anemia; high levels may indicate polycythemia, dehydration, or living at high altitude." },
    { param: "Hematocrit ✓", unit: "%", women: "36-46", men: "41-53", comment: "Percentage of blood volume occupied by red blood cells", explanation: "Percentage of blood volume occupied by red blood cells. Reflects both red cell number and size. Used to assess hydration status, blood loss, and response to anemia treatment." },
    { param: "Red Blood Cells (RBC) ✓", unit: "10^6/µL", women: "4.0-5.2", men: "4.5-5.9", comment: "Cells responsible for oxygen transport", explanation: "Cells responsible for oxygen transport throughout the body. Number affected by erythropoietin, iron status, and bone marrow function." },
    { param: "Mean Corpuscular Volume (MCV) ✓ ⭐", unit: "fL", women: "80-100", men: "80-100", comment: "Average size of red blood cells", explanation: "Average size of red blood cells. Helps classify anemias: microcytic (small cells, often iron deficiency), normocytic (normal size), or macrocytic (large cells, often B12/folate deficiency)." },
    { param: "Mean Corpuscular Hemoglobin (MCH) ✓", unit: "pg", women: "27-33", men: "27-33", comment: "Average hemoglobin amount per RBC", explanation: "Average amount of hemoglobin per red blood cell. Correlates with MCV and helps classify anemias. Low in iron deficiency and thalassemias; high in B12/folate deficiency." },
    { param: "Mean Corpuscular Hemoglobin Concentration (MCHC) ✓", unit: "g/dL", women: "32-36", men: "32-36", comment: "Average hemoglobin concentration in RBCs", explanation: "Average concentration of hemoglobin in red blood cells. Less affected by cell size than MCH. Low in iron deficiency; high in hereditary spherocytosis." },
    { param: "Red Cell Distribution Width (RDW) ✓ ⭐", unit: "%", women: "11.5-14.5", men: "11.5-14.5", comment: "Variation in red blood cell size", explanation: "Measure of variation in red blood cell size. Elevated early in nutritional deficiencies and in mixed anemias. Emerging as independent predictor of mortality in various conditions." },
    { param: "White Blood Cells (WBC) ✓ ⭐", unit: "10^3/µL", women: "4.0-11.0", men: "4.0-11.0", comment: "Immune system cells that fight infections", explanation: "Cells of the immune system that protect against infection and respond to foreign substances. Elevated in infection, inflammation, and leukemia; decreased in bone marrow suppression." },
    { param: "Neutrophils ✓", unit: "%", women: "40-60", men: "40-60", comment: "First responders to bacterial infections", explanation: "Most abundant type of white blood cell. First responders to bacterial infections and tissue damage. Elevated in bacterial infections, inflammation, and stress; decreased in viral infections." },
    { param: "Lymphocytes ✓ ⭐", unit: "%", women: "20-40", men: "20-40", comment: "T cells and B cells of adaptive immunity", explanation: "White blood cells responsible for adaptive immunity. Include T cells, B cells, and natural killer cells. Elevated in viral infections and certain leukemias; decreased in HIV and stress." },
    { param: "Monocytes ✓", unit: "%", women: "2-8", men: "2-8", comment: "Phagocytic cells that become macrophages", explanation: "Large white blood cells that can differentiate into macrophages and dendritic cells. Important for phagocytosis and antigen presentation. Elevated in chronic infections." },
    { param: "Eosinophils ✓", unit: "%", women: "1-4", men: "1-4", comment: "Respond to parasites and allergies", explanation: "White blood cells involved in allergic responses, parasitic infections, and tissue repair. Elevated in allergies, parasitic infections, and certain autoimmune conditions." },
    { param: "Basophils ✓", unit: "%", women: "0.5-1", men: "0.5-1", comment: "Release histamine in allergic reactions", explanation: "Least common type of white blood cell. Release histamine and other mediators during allergic reactions. Elevated in myeloproliferative disorders and certain allergic reactions." },
    { param: "Platelets ✓ ⭐", unit: "10^3/µL", women: "150-450", men: "150-450", comment: "Blood cells for clotting", explanation: "Cell fragments essential for blood clotting and vascular repair. Low levels increase bleeding risk; high levels increase thrombosis risk. Also involved in inflammation and tissue regeneration." },
    { param: "Mean Platelet Volume (MPV) ✓", unit: "fL", women: "7.5-11.5", men: "7.5-11.5", comment: "Average size of platelets", explanation: "Average size of platelets. Larger platelets are generally younger and more reactive. Elevated in conditions with increased platelet turnover; decreased in certain bone marrow disorders." }
  ],
  
  // Hormones Reference Parameters
  hormones: [
    { param: "DHEA-S ⭐", unit: "µg/dl", women: "35.4–256 (age-dependent, optimal upper third)", men: "44.3–331 (age-dependent, optimal upper third)", comment: "Most abundant steroid hormone in the body", explanation: "Most abundant steroid hormone in the body. Precursor to testosterone and estrogen. Levels naturally decline with age. Supports immune function, brain health, and stress resilience." },
    { param: "Total Testosterone", unit: "ng/ml", women: "under 50: 0.5–2\nover 50: 0.4–2", men: "3.0–9.0", comment: "Target: upper range", explanation: "Primary male sex hormone, important for both sexes. Influences muscle mass, bone density, fat distribution, red blood cell production, and libido. In women, excess can indicate PCOS." },
    { param: "Free Testosterone ⭐", unit: "pg/ml", women: "2–4", men: "8–30 (age-dependent)", comment: "Biologically active form, important for metabolic health", explanation: "Biologically active form not bound to carrier proteins. More accurate indicator of testosterone activity than total testosterone. Critical for metabolic health in both sexes." },
    { param: "Estradiol (E2) ⭐", unit: "pg/ml", women: "Follicular phase: 12–170\nOvulation: 100–500\nLuteal phase: 40–200\nPostmenopause: up to 40", men: "up to 40\noptimal: 20–25", comment: "Important for bone density and cardiovascular health", explanation: "Primary female sex hormone, important for both sexes. Influences bone density, cardiovascular health, cognitive function, and mood. In men, excess can indicate aromatase overactivity." },
    { param: "Progesterone", unit: "ng/ml", women: "2nd half of cycle: >10\nHRT: 2–6", men: "1–2", comment: "Balances estrogen effects, important for sleep and mood", explanation: "Balances estrogen effects. Important for sleep, mood, and fluid balance. In women, low levels can contribute to PMS, irregular cycles, and infertility. Precursor to cortisol and aldosterone." },
    { param: "SHBG ⭐", unit: "nmol/l", women: "30–130", men: "20–75", comment: "Regulates bioavailability of sex hormones", explanation: "Binds to sex hormones, regulating their bioavailability. High levels reduce free hormone availability. Influenced by estrogen (increases) and insulin/testosterone (decreases)." },
    { param: "Cortisol (morning)", unit: "µg/dl", women: "16–18", men: "17–18", comment: "Primary stress hormone with diurnal rhythm", explanation: "Primary stress hormone with diurnal rhythm. Influences metabolism, immune function, and blood pressure. Chronic elevation can lead to insulin resistance, immune suppression, and cognitive issues." },
    { param: "FSH", unit: "mIU/ml", women: "Follicular phase: 3–15\nOvulation: 4–23\nLuteal phase: 1.5–9\nPostmenopause: up to 100", men: "up to 10", comment: "On HRT: 40–60", explanation: "Stimulates follicle development in women and sperm production in men. Elevated levels in women can indicate diminished ovarian reserve or menopause. Works with LH in reproductive function." },
    { param: "LH", unit: "mIU/ml", women: "Follicular phase: 2.5–13\nOvulation: 9–70\nLuteal phase: 1–13\nPostmenopause: 16–55", men: "1.5–10", comment: "FSH/LH ratio 2:1", explanation: "Triggers ovulation in women and stimulates testosterone production in men. LH:FSH ratio important for diagnosing PCOS and other hormonal imbalances. Pulsatile secretion affects measurement." },
    { param: "HbA1c ⭐", unit: "%", women: "<5.6", men: "<5.6", comment: "<5.7", explanation: "Reflects average blood glucose over previous 2-3 months. Important marker for diabetes risk and management. Values between 5.7-6.4% indicate prediabetes; ≥6.5% diagnostic for diabetes." }
  ],

  // Notes and additional text
  notes: {
    title: "Instructions for use:",
    note1: "These values are based on the latest epigenetic and macromolecular research from orthomolecular medicine experts.",
    note2: "For individual interpretation, always consider personal history and clinical context.",
    note3: "For hormones, consider cycle phase, age, and possible hormone therapy, especially for women.",
    note4: "Amino acids: For optimal health, each amino acid should be in the upper half of the reference range; values are based on healthy, high-performing individuals.",
    note5: "Special vitamins: Target values are often higher than standard reference ranges to support prevention and optimal function.",
    note6: "Inflammation markers: Lower values are generally better; chronic low-grade inflammation is a risk factor for many diseases.",
    indicators: "Indicators: ✓ Tests paid by public health insurance, ⭐ Tests highly recommended by experts",
    sources: "Sources: Nutrient Therapy - The Practice Guide, Dr. Helena Orfanos-Boeckel (2023); The Blood Value Code, Thiemo Osterhaus (2023); Nutrient Therapy, Dr. Helena Orfanos-Boeckel (2022), Dr. Ulrich Strunz, \"The Amino Revolution\" (2022)"
  }
};

export default reference;
