
const en = {
  "app.title": "Blood Test Oracle",
  "app.subtitle": "Medical Analysis Tool",
  "page.title": "Blood Test Analysis",
  "page.description": "Enter your blood test values or upload test results for instant analysis and interpretation",
  "learn.more": "Learn more",
  "language.toggle": "EN",
  "dialog.title": "Welcome to mabu.red",
  "disclaimer.title": "Disclaimer",
  "back.to.test": "Back to Test Input",
  "footer.text": "Blood Test Oracle - A medical analysis tool for educational purposes",
  
  // New translations
  "disclaimer.paragraph1": "This app is intended for experimental and educational purposes only. The information and responses provided by this app are generated by artificial intelligence and are not intended as, nor should they be considered, professional medical advice, diagnosis, or treatment.",
  "disclaimer.paragraph2": "This app does not replace consultation with a licensed healthcare provider or medical expert. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition or before making any changes to your health regimen.",
  "disclaimer.paragraph3": "Never disregard professional medical advice or delay in seeking it because of something you have read or received from this app. Use of this app and reliance on any information provided is solely at your own risk.",
  "disclaimer.paragraph4": "If you are experiencing a medical emergency, call your doctor or emergency services immediately.",
  
  "blood.test.title": "Blood Test Values",
  "blood.test.submit": "Submit Blood Test Results",
  "select.date": "Select Test Date",
  "entry.methods": "Entry Methods",
  "manual.entry": "Manual Entry",
  "file.upload": "File Upload",
  
  "gender.reference": "Reference values for:",
  "gender.female": "Female",
  "gender.male": "Male",
  "gender.info": "Show reference information",
  "gender.info.text": "Reference values may vary based on gender.",
  
  "upload.title": "Upload Test Results",
  "upload.instructions": "Drag and drop your blood test PDF or image file here, or click to select",
  "upload.button": "Upload and Extract",
  
  "timeline.title": "Blood Test Timeline",
  "timeline.description": "Track your blood test results over time",
  "timeline.back": "Back to Results",
  "timeline.add": "Save Current Results",
  "timeline.select": "Select a test result to view details",
  "timeline.date": "Test Date",
  
  "edit.title": "Edit Test Results",
  "edit.description": "Modify the values for this test.",
  "edit.cancel": "Cancel",
  
  "welcome.intro": "Where cutting-edge research in epigenetics, longevity, and molecular medicine converges to empower healthier, longer lives.",
  "welcome.paragraph1": "Aging is shaped not just by our genes but by dynamic interactions between epigenetic switches, environmental factors, and cellular health. Emerging science reveals that longevity hinges on maintaining biomarker balance – measurable indicators like DNA methylation patterns, nutrient levels, and hormonal activity. These biomarkers act as a \"health dashboard,\" revealing gaps in essential nutrients (e.g., vitamin D, magnesium), amino acids, and hormones that accelerate aging if unaddressed.",
  "welcome.strategies.title": "Personalized Health Strategies",
  "welcome.strategies.item1": "Biomarker Diagnostics: Advanced testing pinpoints deficiencies in nutrients (e.g., iron, B vitamins), antioxidants, and hormones like cortisol, enabling tailored interventions.",
  "welcome.strategies.item2": "Micronutrient Optimization: Targeted supplements – such as resveratrol (DNA repair), omega-3s (brain health), and CoQ10 (cellular energy) – address gaps identified through testing.",
  "welcome.strategies.item3": "Hormonal & Metabolic Balance: Lifestyle adjustments restore rhythm to systems disrupted by aging, including insulin sensitivity and stress response.",
  "welcome.practices.title": "Science-Backed Longevity Practices",
  "welcome.practices.item1": "Movement: Regular exercise boosts mitochondrial health and muscle-derived antioxidants like EcSOD, reducing oxidative stress.",
  "welcome.practices.item2": "Sleep Optimization: 7+ hours nightly lowers mortality risk by 18% and supports metabolic repair.",
  "welcome.practices.item3": "Stress Resilience: Techniques like active rest (light yoga, walking) and mindfulness modulate inflammation linked to chronic disease.",
  "welcome.outro": "By bridging biomarker gaps and aligning lifestyle with cellular needs, we unlock possibilities for healthspan extension. Explore how these insights apply to your unique biology – ready to dive deeper?",
  
  "results.notice.title": "Important Notice",
  "results.notice.text": "This analysis is for informational purposes only and is not a substitute for professional medical advice. Always consult with your healthcare provider regarding your blood test results.",
  "results.status.normal": "Normal",
  "results.status.low": "Low",
  "results.status.high": "High",
  "results.value": "Value:",
  "results.range": "Normal range:"
};

export default en;
