// Autogenerated type for longevity locale
// You may expand this for other locales as needed
import longevityJson from '../locales/en/longevity.json';

export type NamespaceLongevity = typeof longevityJson;
