
import React from "react";
import { Alert, AlertTitle, AlertDescription } from "@/components/ui/alert";
import { Info } from "lucide-react";
import { useLanguage } from "@/context/LanguageContext";

const disclaimerText = {
  en: {
    title: "Disclaimer",
    paragraph1: "This app is intended for experimental and educational purposes only. The information and responses provided by this app are generated by artificial intelligence and are not intended as, nor should they be considered, professional medical advice, diagnosis, or treatment.",
    paragraph2: "This app does not replace consultation with a licensed healthcare provider or medical expert. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition or before making any changes to your health regimen.",
    paragraph3: "Never disregard professional medical advice or delay in seeking it because of something you have read or received from this app. Use of this app and reliance on any information provided is solely at your own risk.",
    paragraph4: "If you are experiencing a medical emergency, call your doctor or emergency services immediately."
  },
  de: {
    title: "Haftungsausschluss",
    paragraph1: "Diese App ist nur für experimentelle und pädagogische Zwecke gedacht. Die von dieser App bereitgestellten Informationen und Antworten werden von künstlicher Intelligenz generiert und sind nicht als professionelle medizinische Beratung, Diagnose oder Behandlung gedacht oder zu betrachten.",
    paragraph2: "Diese App ersetzt nicht die Konsultation eines lizenzierten Gesundheitsdienstleisters oder medizinischen Experten. Wenden Sie sich immer an Ihren Arzt oder einen anderen qualifizierten Gesundheitsdienstleister, wenn Sie Fragen zu einem medizinischen Zustand haben oder bevor Sie Änderungen an Ihrem Gesundheitsregime vornehmen.",
    paragraph3: "Ignorieren Sie niemals professionellen medizinischen Rat oder verzögern Sie die Suche danach aufgrund von etwas, das Sie von dieser App gelesen oder erhalten haben. Die Nutzung dieser App und das Vertrauen auf die bereitgestellten Informationen erfolgt ausschließlich auf eigenes Risiko.",
    paragraph4: "Wenn Sie einen medizinischen Notfall haben, rufen Sie sofort Ihren Arzt oder den Notdienst an."
  },
  fr: {
    title: "Avertissement",
    paragraph1: "Cette application est destinée uniquement à des fins expérimentales et éducatives. Les informations et les réponses fournies par cette application sont générées par l'intelligence artificielle et ne sont pas destinées à être, ni ne doivent être considérées comme, des conseils, diagnostics ou traitements médicaux professionnels.",
    paragraph2: "Cette application ne remplace pas la consultation d'un professionnel de la santé agréé ou d'un expert médical. Consultez toujours votre médecin ou un autre professionnel de la santé qualifié pour toute question concernant une condition médicale ou avant d'apporter des modifications à votre régime de santé.",
    paragraph3: "Ne négligez jamais un avis médical professionnel ou ne tardez pas à le consulter en raison de quelque chose que vous avez lu ou reçu de cette application. L'utilisation de cette application et la confiance accordée aux informations fournies sont entièrement à vos propres risques.",
    paragraph4: "Si vous êtes confronté à une urgence médicale, appelez immédiatement votre médecin ou les services d'urgence."
  }
};

const Disclaimer = () => {
  const { language } = useLanguage();
  
  const languageKey = (language in disclaimerText) ? language : "en";
  const currentText = disclaimerText[languageKey as keyof typeof disclaimerText];

  return (
    <Alert className="mt-12 border-2 border-blue-200 bg-blue-50">
      <Info className="h-5 w-5 text-blue-800" />
      <AlertTitle className="text-lg font-semibold text-blue-800">{currentText.title}</AlertTitle>
      <AlertDescription className="mt-3 space-y-4 text-blue-700">
        <p>{currentText.paragraph1}</p>
        <p>{currentText.paragraph2}</p>
        <p>{currentText.paragraph3}</p>
        <p className="font-medium">{currentText.paragraph4}</p>
      </AlertDescription>
    </Alert>
  );
};

export default Disclaimer;
