
import React from "react";
import { Alert, AlertTitle, AlertDescription } from "@/components/ui/alert";
import { Info } from "lucide-react";

const Disclaimer = () => {
  return (
    <Alert className="mt-12 border-2 border-blue-200 bg-blue-50">
      <Info className="h-5 w-5 text-blue-800" />
      <AlertTitle className="text-lg font-semibold text-blue-800">Disclaimer</AlertTitle>
      <AlertDescription className="mt-3 space-y-4 text-blue-700">
        <p>
          This app is intended for experimental and educational purposes only. The information and responses provided by this app are generated by artificial intelligence and are not intended as, nor should they be considered, professional medical advice, diagnosis, or treatment.
        </p>
        <p>
          This app does not replace consultation with a licensed healthcare provider or medical expert. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition or before making any changes to your health regimen.
        </p>
        <p>
          Never disregard professional medical advice or delay in seeking it because of something you have read or received from this app. Use of this app and reliance on any information provided is solely at your own risk.
        </p>
        <p className="font-medium">
          If you are experiencing a medical emergency, call your doctor or emergency services immediately.
        </p>
      </AlertDescription>
    </Alert>
  );
};

export default Disclaimer;
