
const reference = {
  // Reference values dialog
  "reference.title": "Referenzwerte",
  "reference.description": "Basierend auf den Empfehlungen von Dr. Ulrich Strunz und Dr. med. Helena Orfanos-Boeckel",
  "reference.general": "Allgemeine Parameter",
  "reference.amino": "Aminosäuren",
  "reference.vitamins": "Spezielle Vitamine",
  "reference.inflammation": "Entzündungsmarker",
  "reference.hematology": "Hämatologie",
  "reference.hormones": "Hormone",
  "reference.caption.general": "Referenzwerte für Allgemeine Parameter",
  "reference.caption.amino": "Referenzwerte für Aminosäuren (Aminogramm, Serum/Plasma)",
  "reference.caption.vitamins": "Referenzwerte für Spezielle Vitamine",
  "reference.caption.inflammation": "Referenzwerte für Entzündungsmarker",
  "reference.caption.hematology": "Referenzwerte für Hämatologie",
  "reference.caption.hormones": "Referenzwerte für Hormone",
  "reference.column.parameter": "Parameter",
  "reference.column.unit": "Einheit",
  "reference.column.women": "Frauen (Referenz/Ziel)",
  "reference.column.men": "Männer (Referenz/Ziel)",
  "reference.column.comment": "Kommentar",
  "reference.notes.title": "Hinweise zur Verwendung:",
  "reference.notes.1": "Diese Werte basieren auf dem neuesten Stand der epigenetischen und makromolekularen Forschung aus der orthomolekularen Medizin.",
  "reference.notes.2": "Berücksichtigen Sie für die individuelle Interpretation immer die persönliche Vorgeschichte und den klinischen Kontext.",
  "reference.notes.3": "Bei Hormonen berücksichtigen Sie Zyklusphase, Alter und mögliche Hormontherapie, besonders bei Frauen.",
  "reference.notes.4": "Aminosäuren: Für optimale Gesundheit sollte jede Aminosäure in der oberen Hälfte des Referenzbereichs liegen; Werte basieren auf gesunden, leistungsstarken Individuen.",
  "reference.notes.5": "Spezielle Vitamine: Zielwerte liegen oft höher als Standard-Referenzbereiche, um Prävention und optimale Funktion zu unterstützen.",
  "reference.notes.6": "Entzündungsmarker: Niedrigere Werte sind generell besser; chronische niedriggradige Entzündungen sind ein Risikofaktor für viele Krankheiten.",
  "reference.notes.indicators": "Indikatoren: ✓ Tests werden von der gesetzlichen Krankenversicherung bezahlt, ⭐ Tests werden von Experten besonders empfohlen",
  "reference.sources": "Quellen: Nährstoff-Therapie – Der Praxisleitfaden, Dr. med. Helena Orfanos-Boeckel (2023); Der Blutwerte-Code, Thiemo Osterhaus (2023); Nährstoff-Therapie, Dr. med. Helena Orfanos-Boeckel (2022), Dr. Ulrich Strunz, \"Die Amino-Revolution\" (2022)",
  "gender.male": "Männlich",
  "gender.female": "Weiblich",

  // German table data
  "general": [
    { param: "Ferritin ⭐", unit: "ng/ml", women: "prämenopausal: 15–150\npostmenopausal: 15–300\noptimal: 70–200", men: "30–400\noptimal: 100–300", comment: "Eisenspeicherprotein", explanation: "Eisenspeicherprotein; spiegelt Gesamtkörper-Eisenspeicher wider. Niedrige Werte weisen auf Eisenmangel vor der Anämie hin. Hohe Werte können auf Entzündungen, Infektionen oder Eisenüberladungen hinweisen." },
    { param: "TSH ⭐", unit: "mIU/l", women: "0,5–2,5 (optimal)", men: "0,5–2,5 (optimal)", comment: "Schilddrüsenstimulierendes Hormon", explanation: "Hauptregulator der Schilddrüsenfunktion. Erhöhte Werte deuten auf Hypothyreose (Unterfunktion) hin; niedrige Werte deuten auf Hyperthyreose (Überfunktion) hin." },
    { param: "Vitamin D (25-OH) ⭐", unit: "ng/ml", women: "50–70 (optimal)", men: "50–70 (optimal)", comment: "Vitamin-D-Status", explanation: "Essentiell für Kalziumaufnahme, Knochengesundheit, Immunfunktion und Genexpression. Beeinflusst über 2000 Gene und hat Rezeptorstellen in nahezu jeder Zelle. Mangel ist mit zahlreichen chronischen Erkrankungen verbunden." },
    { param: "Vitamin B12 ⭐", unit: "pg/ml", women: ">600 (optimal 1000)", men: ">600 (optimal 1000)", comment: "Vitamin-B12-Status", explanation: "Wichtig für Nervenfunktion, DNA-Synthese und Bildung roter Blutkörperchen. Funktioneller Mangel kann auch bei 'normalen' Werten auftreten; aktives B12 (Holotranscobalamin) ist genauer." },
    { param: "Holo-transcobalamin", unit: "pmol/l", women: ">100", men: ">100", comment: "Aktives B12", explanation: "Aktive Form von B12, die von Zellen genutzt werden kann. Genauerer Indikator für den B12-Status als Gesamt-B12. Essentiell für Methylierungsprozesse und neurologische Gesundheit." },
    { param: "Folsäure ⭐", unit: "ng/ml", women: ">16", men: ">16", comment: "Folsäure-Status", explanation: "Entscheidend für DNA-Synthese, -Reparatur und Methylierung. Arbeitet synergistisch mit B12. Wichtig für die kardiovaskuläre Gesundheit durch Homocystein-Regulierung." },
    { param: "Zink ⭐", unit: "mg/l", women: "6–7", men: "6–7", comment: "Zink-Status", explanation: "Wichtig für Immunfunktion, Proteinsynthese, Wundheilung, DNA-Synthese und Zellteilung. Kofaktor für über 300 Enzyme. Serumwerte spiegeln möglicherweise nicht den Gewebsstatus wider." },
    { param: "Magnesium (Vollblut) ⭐", unit: "mmol/l", women: "0,85–1,0", men: "0,85–1,0", comment: "Magnesium-Status", explanation: "Erforderlich für über 600 enzymatische Reaktionen. Kritisch für Energieproduktion, Muskelfunktion, Nervenübertragung und Knochenbildung. Serumwerte repräsentieren nur 1% des Körpermagnesiums." },
    { param: "Selen ⭐", unit: "µg/l", women: "140–160", men: "140–160", comment: "Selen-Status", explanation: "Antioxidatives Mineral, wesentlich für Schilddrüsenhormonstoffwechsel, Immunfunktion und Fruchtbarkeit. Bestandteil von Glutathionperoxidase-Enzymen, die vor oxidativen Schäden schützen." },
    { param: "Omega-3-Index ⭐", unit: "%", women: ">8", men: ">8", comment: "Omega-3-Status", explanation: "Misst EPA und DHA in Erythrozytenmembranen. Spiegelt den langfristigen Omega-3-Status wider. Höhere Werte sind mit reduziertem kardiovaskulärem Risiko, verbesserter kognitiver Funktion und reduzierter Entzündung verbunden." },
    { param: "Gesamtprotein", unit: "g/dl", women: ">7,0 (optimal 7,3–7,6)", men: ">7,0 (optimal 7,3–7,6)", comment: "Gesamtproteinstatus", explanation: "Summe aller Proteine im Blut, hauptsächlich Albumin und Globuline. Indikator für Ernährungszustand, Leberfunktion und Hydratation. Niedrige Werte können auf Mangelernährung oder proteinverlierende Zustände hinweisen." }
  ],

  "amino": [
    { param: "Leucin", unit: "µmol/L", women: "110–217 (Ziel: obere Hälfte)", men: "110–217 (Ziel: obere Hälfte)", comment: "BCAA, wichtig für Muskelproteinsynthese", explanation: "Kritisch für Muskelproteinsynthese und Energieproduktion während des Trainings. Aktiviert direkt den mTOR-Signalweg für Muskelwachstum und -regeneration." },
    { param: "Isoleucin", unit: "µmol/L", women: "58–117 (Ziel: obere Hälfte)", men: "58–117 (Ziel: obere Hälfte)", comment: "BCAA, unterstützt Glukoseaufnahme im Muskel", explanation: "Unterstützt Glukoseaufnahme im Muskel, Wundheilung und Immunfunktion. Wichtig für Hämoglobinbildung und Energieregulierung." },
    { param: "Valin", unit: "µmol/L", women: "206–317 (Ziel: obere Hälfte)", men: "206–317 (Ziel: obere Hälfte)", comment: "BCAA, unterstützt Stickstoffbilanz und Immunsystem", explanation: "Unterstützt Stickstoffbilanz, Muskelstoffwechsel und kognitive Funktion. Wichtig für Immunsystemfunktion und Gewebereparatur." },
    { param: "Methionin", unit: "µmol/L", women: "25–40 (Ziel: obere Hälfte)", men: "25–40 (Ziel: obere Hälfte)", comment: "Schwefelhaltige Aminosäure für Methylierungsprozesse", explanation: "Schwefelhaltige Aminosäure, kritisch für Methylierungsprozesse, Entgiftung und Antioxidantienproduktion. Vorstufe zu Cystein und Glutathion." },
    { param: "Lysin", unit: "µmol/L", women: "139–240 (Ziel: obere Hälfte)", men: "139–240 (Ziel: obere Hälfte)", comment: "Erforderlich für Kollagenbildung und Immunfunktion", explanation: "Erforderlich für Kollagenbildung, Kalziumaufnahme und Proteinsynthese. Unterstützt die Immunfunktion und kann bei der Bewältigung von Herpesvirus-Infektionen helfen." },
    { param: "Phenylalanin", unit: "µmol/L", women: "51–109 (Ziel: obere Hälfte)", men: "51–109 (Ziel: obere Hälfte)", comment: "Vorstufe zu Tyrosin, Dopamin und anderen Neurotransmittern", explanation: "Vorstufe zu Tyrosin, Dopamin, Noradrenalin und Adrenalin. Wichtig für kognitive Funktion und Stimmungsregulation." },
    { param: "Tryptophan", unit: "µmol/L", women: "36–125 (Ziel: obere Hälfte)", men: "36–125 (Ziel: obere Hälfte)", comment: "Vorstufe zu Serotonin und Melatonin, Stimmungsregulation", explanation: "Vorstufe zu Serotonin und Melatonin. Kritisch für Stimmungsregulation, Schlafqualität und Stressresistenz." },
    { param: "Threonin", unit: "µmol/L", women: "118–210 (Ziel: obere Hälfte)", men: "118–210 (Ziel: obere Hälfte)", comment: "Wichtig für Kollagen, Elastin und Antikörperproduktion", explanation: "Wichtig für Kollagen-, Elastin- und Antikörperproduktion. Unterstützt Darmschleimhautintegrität und Immunfunktion." },
    { param: "Histidin", unit: "µmol/L", women: "60–110 (Ziel: obere Hälfte)", men: "60–110 (Ziel: obere Hälfte)", comment: "Bestandteil von Hämoglobin, Myelinscheidenerhaltung", explanation: "Bestandteil von Hämoglobin. Wichtig für die Erhaltung der Myelinscheide und die Histaminproduktion." },
    { param: "Arginin", unit: "µmol/L", women: "110–180 (Ziel: obere Hälfte)", men: "110–180 (Ziel: obere Hälfte)", comment: "Vorstufe zu Stickstoffmonoxid, verbessert Gefäßfunktion", explanation: "Vorstufe zu Stickstoffmonoxid, verbessert die Gefäßfunktion und Durchblutung. Unterstützt Wundheilung und Immunfunktion." },
    { param: "Glutamin", unit: "µmol/L", women: "500–900 (Ziel: obere Hälfte)", men: "500–900 (Ziel: obere Hälfte)", comment: "Primärer Brennstoff für Darm- und Immunzellen", explanation: "Häufigste Aminosäure im Blut. Primärer Brennstoff für Darmzellen und Immunzellen." }
  ],

  "vitamins": [
    { param: "Vitamin A (Retinol)", unit: "µg/L", women: "700–900 (optimal: 800)", men: "700–900 (optimal: 800)", comment: "Essentiell für Sehvermögen, Immunfunktion, zelluläre Differenzierung", explanation: "Fettlösliches Vitamin, essentiell für Sehvermögen, Immunfunktion, zelluläre Differenzierung und Genexpression. Wirkt als Antioxidans und unterstützt die Integrität des Epithelgewebes." },
    { param: "Vitamin B1 (Thiamin, aktiv)", unit: "µg/L", women: "39,8–60 (Ziel: 60)", men: "39,8–60 (Ziel: 60)", comment: "Wichtig für Kohlenhydratstoffwechsel und Nervenfunktion", explanation: "Wasserlösliches Vitamin, kritisch für Kohlenhydratstoffwechsel und Energieproduktion. Essentiell für Nervenfunktion, Herzgesundheit und Glukosestoffwechsel." },
    { param: "Vitamin B2 (Riboflavin, aktiv)", unit: "µg/L", women: "85–300 (Ziel: 250)", men: "85–300 (Ziel: 250)", comment: "Beteiligt an Energieproduktion und antioxidativer Funktion", explanation: "Wasserlösliches Vitamin, beteiligt an Energieproduktion, Zellwachstum und antioxidativer Funktion. Kofaktor für zahlreiche Redox-Reaktionen." },
    { param: "Vitamin B6 (P5P, aktiv)", unit: "µg/L", women: "10,1–36 (Ziel: 36)", men: "10,1–36 (Ziel: 36)", comment: "Essentiell für Aminosäurenstoffwechsel und Neurotransmittersynthese", explanation: "Wasserlösliches Vitamin, beteiligt an über 100 Enzymreaktionen. Aktive Form (P5P) essentiell für Aminosäurestoffwechsel, Neurotransmittersynthese und Homocysteinregulation." },
    { param: "Vitamin B9 (Folat, aktiv)", unit: "µg/L", women: "100–270 (Ziel: 160)", men: "100–270 (Ziel: 160)", comment: "Wichtig für DNA-Synthese, -Reparatur und Methylierung", explanation: "Wasserlösliches Vitamin, kritisch für DNA-Synthese, -Reparatur und Methylierung. Aktive Form (5-MTHF) ist wirksamer als synthetische Folsäure." },
    { param: "Vitamin B12 (aktiv, Holo-TC)", unit: "pmol/L", women: ">100 (Ziel: 100–150)", men: ">100 (Ziel: 100–150)", comment: "Essentiell für Nervenfunktion, DNA-Synthese und Methylierung", explanation: "Wasserlösliches Vitamin, essentiell für Nervenfunktion, DNA-Synthese und Bildung roter Blutkörperchen. Aktive Form (Holotranscobalamin) repräsentiert bioverfügbares B12." },
    { param: "Vitamin C", unit: "mg/L", women: "10–20 (Ziel: 10–20, bis zu 100 möglich)", men: "10–20 (Ziel: 10–20, bis zu 100 möglich)", comment: "Starkes Antioxidans, essentiell für Kollagensynthese", explanation: "Wasserlösliches Vitamin und starkes Antioxidans. Essentiell für Kollagensynthese, Immunfunktion und Neurotransmitterproduktion. Regeneriert andere Antioxidantien." },
    { param: "Vitamin E", unit: "mg/L", women: "16–25 (Ziel: 16–25)", men: "16–25 (Ziel: 16–25)", comment: "Schützt Zellmembranen vor oxidativen Schäden", explanation: "Fettlösliches Antioxidans, das Zellmembranen vor oxidativen Schäden schützt. Acht verschiedene Formen mit unterschiedlicher biologischer Aktivität." },
    { param: "Vitamin K2 (MK-7)", unit: "ng/L", women: "1000–6000 (Ziel: >1000)", men: "1000–6000 (Ziel: >1000)", comment: "Essentiell für Kalziumregulation und kardiovaskuläre Gesundheit", explanation: "Fettlösliches Vitamin, essentiell für die Kalziumregulation. Leitet Kalzium zu Knochen und weg von Weichgeweben. MK-7-Form hat längere Halbwertszeit und größere Bioaktivität als MK-4." }
  ],

  "inflammation": [
    { param: "CRP (C-reaktives Protein, hsCRP)", unit: "mg/L", women: "<1,0 (optimal: <0,8)", men: "<1,0 (optimal: <0,8)", comment: "Empfindlicher Marker für systemische Entzündung", explanation: "Empfindlicher Marker für systemische Entzündung, produziert von der Leber. Erhöht bei Infektion, Gewebeschäden und chronischer Entzündung." },
    { param: "BDNF (Brain-derived neurotrophic factor)", unit: "ng/ml", women: "30–40 (Ziel)", men: "30–40 (Ziel)", comment: "Protein zur Unterstützung des neuronalen Wachstums und der Neuroplastizität", explanation: "Protein, das das Überleben und Wachstum von Neuronen unterstützt. Wichtig für Neuroplastizität, Lernen und Gedächtnis. Werte werden durch Bewegung, Stress, Schlafqualität und Entzündung beeinflusst." },
    { param: "AGEs (Advanced glycation endproducts)", unit: "µg/ml", women: "<50 (je niedriger, desto besser)", men: "<50 (je niedriger, desto besser)", comment: "Verbindungen im Zusammenhang mit Alterung und Gewebeschäden", explanation: "Verbindungen, die entstehen, wenn Zucker ohne Enzymkontrolle mit Proteinen oder Lipiden reagiert. Tragen zu Alterung, Entzündung und Gewebeschäden bei." },
    { param: "Nitrotyrosin", unit: "nmol/L", women: "<200 (Ziel)", men: "<200 (Ziel)", comment: "Marker für Proteinoxidation und nitrosativen Stress", explanation: "Marker für Proteinoxidation und nitrosativen Stress. Entsteht, wenn Peroxynitrit Tyrosinreste in Proteinen modifiziert. Erhöht bei chronischer Entzündung." },
    { param: "Zonulin (Marker für Leaky Gut)", unit: "ng/ml", women: "<30 (je niedriger, desto besser)", men: "<30 (je niedriger, desto besser)", comment: "Zeigt intestinale Permeabilität an", explanation: "Protein, das Tight Junctions zwischen Darmzellen reguliert. Erhöhte Werte weisen auf erhöhte intestinale Permeabilität (\"Leaky Gut\") hin." }
  ],

  "hematology": [
    { param: "Hämoglobin ✓ ⭐", unit: "g/dL", women: "12,0-15,5", men: "13,5-17,5", comment: "Sauerstoffträgerprotein in roten Blutkörperchen", explanation: "Protein in roten Blutkörperchen, das Sauerstoff von der Lunge zu den Geweben transportiert. Niedrige Werte weisen auf Anämie hin; hohe Werte können auf Polyzythämie, Dehydration oder Leben in großer Höhe hinweisen." },
    { param: "Hämatokrit ✓", unit: "%", women: "36-46", men: "41-53", comment: "Prozentualer Anteil des Blutvolumens, der von Erythrozyten eingenommen wird", explanation: "Prozentualer Anteil des Blutvolumens, der von roten Blutkörperchen eingenommen wird. Spiegelt sowohl die Anzahl als auch die Größe der roten Zellen wider. Wird zur Beurteilung des Hydrationszustands, Blutverlusts und der Reaktion auf Anämiebehandlung verwendet." },
    { param: "Rote Blutkörperchen (RBC) ✓", unit: "10^6/µL", women: "4,0-5,2", men: "4,5-5,9", comment: "Zellen verantwortlich für den Sauerstofftransport", explanation: "Zellen, die für den Sauerstofftransport im gesamten Körper verantwortlich sind. Anzahl wird durch Erythropoetin, Eisenstatus und Knochenmarkfunktion beeinflusst." },
    { param: "Mittleres Korpuskuläres Volumen (MCV) ✓ ⭐", unit: "fL", women: "80-100", men: "80-100", comment: "Durchschnittliche Größe der roten Blutkörperchen", explanation: "Durchschnittliche Größe der roten Blutkörperchen. Hilft bei der Klassifizierung von Anämien: mikrozytär (kleine Zellen, oft Eisenmangel), normozytär (normale Größe) oder makrozytär (große Zellen, oft B12/Folsäuremangel)." },
    { param: "Mittleres Korpuskuläres Hämoglobin (MCH) ✓", unit: "pg", women: "27-33", men: "27-33", comment: "Durchschnittliche Hämoglobinmenge pro RBC", explanation: "Durchschnittliche Hämoglobinmenge pro rotem Blutkörperchen. Korreliert mit MCV und hilft bei der Klassifizierung von Anämien. Niedrig bei Eisenmangel und Thalassämien; hoch bei B12/Folsäuremangel." },
    { param: "Mittlere Korpuskuläre Hämoglobinkonzentration (MCHC) ✓", unit: "g/dL", women: "32-36", men: "32-36", comment: "Durchschnittliche Hämoglobinkonzentration in RBCs", explanation: "Durchschnittliche Hämoglobinkonzentration in roten Blutkörperchen. Weniger von der Zellgröße beeinflusst als MCH. Niedrig bei Eisenmangel; hoch bei hereditärer Sphärozytose." },
    { param: "Erythrozyten-Verteilungsbreite (RDW) ✓ ⭐", unit: "%", women: "11,5-14,5", men: "11,5-14,5", comment: "Variation der Größe der roten Blutkörperchen", explanation: "Maß für die Variation in der Größe der roten Blutkörperchen. Früh erhöht bei Nährstoffmangel und bei gemischten Anämien. Entwickelt sich als unabhängiger Prädiktor für die Mortalität bei verschiedenen Erkrankungen." },
    { param: "Weiße Blutkörperchen (WBC) ✓ ⭐", unit: "10^3/µL", women: "4,0-11,0", men: "4,0-11,0", comment: "Immunsystemzellen zur Bekämpfung von Infektionen", explanation: "Zellen des Immunsystems, die vor Infektionen schützen und auf Fremdstoffe reagieren. Erhöht bei Infektion, Entzündung und Leukämie; verringert bei Knochenmarksuppression." },
    { param: "Neutrophile ✓", unit: "%", women: "40-60", men: "40-60", comment: "Ersthelfer bei bakteriellen Infektionen", explanation: "Häufigster Typ weißer Blutkörperchen. Ersthelfer bei bakteriellen Infektionen und Gewebeschäden. Erhöht bei bakteriellen Infektionen, Entzündungen und Stress; verringert bei viralen Infektionen." },
    { param: "Lymphozyten ✓ ⭐", unit: "%", women: "20-40", men: "20-40", comment: "T-Zellen und B-Zellen der adaptiven Immunität", explanation: "Weiße Blutkörperchen, verantwortlich für die adaptive Immunität. Umfassen T-Zellen, B-Zellen und natürliche Killerzellen. Erhöht bei viralen Infektionen und bestimmten Leukämien; verringert bei HIV und Stress." },
    { param: "Monozyten ✓", unit: "%", women: "2-8", men: "2-8", comment: "Phagozytische Zellen, die zu Makrophagen werden", explanation: "Große weiße Blutkörperchen, die sich zu Makrophagen und dendritischen Zellen differenzieren können. Wichtig für Phagozytose und Antigenpräsentation. Erhöht bei chronischen Infektionen." },
    { param: "Eosinophile ✓", unit: "%", women: "1-4", men: "1-4", comment: "Reaktion auf Parasiten und Allergien", explanation: "Weiße Blutkörperchen, beteiligt an allergischen Reaktionen, Parasiteninfektionen und Gewebereparatur. Erhöht bei Allergien, Parasiteninfektionen und bestimmten Autoimmunerkrankungen." },
    { param: "Basophile ✓", unit: "%", women: "0,5-1", men: "0,5-1", comment: "Histaminfreisetzung bei allergischen Reaktionen", explanation: "Seltenster Typ weißer Blutkörperchen. Setzen Histamin und andere Mediatoren während allergischer Reaktionen frei. Erhöht bei myeloproliferativen Störungen und bestimmten allergischen Reaktionen." },
    { param: "Thrombozyten ✓ ⭐", unit: "10^3/µL", women: "150-450", men: "150-450", comment: "Blutzellen für die Blutgerinnung", explanation: "Zellfragmente, die für die Blutgerinnung und Gefäßreparatur unerlässlich sind. Niedrige Werte erhöhen das Blutungsrisiko; hohe Werte erhöhen das Thromboserisiko. Auch beteiligt an Entzündungen und Geweberegeneration." },
    { param: "Mittleres Thrombozytenvolumen (MPV) ✓", unit: "fL", women: "7,5-11,5", men: "7,5-11,5", comment: "Durchschnittliche Größe der Thrombozyten", explanation: "Durchschnittliche Größe der Thrombozyten. Größere Thrombozyten sind in der Regel jünger und reaktiver. Erhöht bei Zuständen mit erhöhtem Thrombozytenumsatz; verringert bei bestimmten Knochenmarkstörungen." }
  ],

  "hormones": [
    { param: "DHEA-S ⭐", unit: "µg/dl", women: "35,4–256 (altersabhängig, optimal oberes Drittel)", men: "44,3–331 (altersabhängig, optimal oberes Drittel)", comment: "Häufigstes Steroidhormon im Körper", explanation: "Häufigstes Steroidhormon im Körper. Vorstufe zu Testosteron und Östrogen. Werte nehmen natürlich mit dem Alter ab. Unterstützt Immunfunktion, Gehirngesundheit und Stressresilienz." },
    { param: "Testosteron gesamt", unit: "ng/ml", women: "bis 50 Jahre: 0,5–2\nüber 50 Jahre: 0,4–2", men: "3,0–9,0", comment: "Ziel: oberer Bereich", explanation: "Primäres männliches Geschlechtshormon, wichtig für beide Geschlechter. Beeinflusst Muskelmasse, Knochendichte, Fettverteilung, Produktion roter Blutkörperchen und Libido. Bei Frauen kann ein Überschuss auf PCOS hinweisen." },
    { param: "Freies Testosteron ⭐", unit: "pg/ml", women: "2–4", men: "8–30 (altersabhängig)", comment: "Biologisch aktive Form, wichtig für metabolische Gesundheit", explanation: "Biologisch aktive Form, die nicht an Trägerproteine gebunden ist. Genauerer Indikator für Testosteronaktivität als Gesamttestosteron. Kritisch für die metabolische Gesundheit beider Geschlechter." },
    { param: "Östradiol (E2) ⭐", unit: "pg/ml", women: "Follikelphase: 12–170\nOvulation: 100–500\nLutealphase: 40–200\nPostmenopause: bis zu 40", men: "bis zu 40\noptimal: 20–25", comment: "Wichtig für Knochendichte und kardiovaskuläre Gesundheit", explanation: "Primäres weibliches Geschlechtshormon, wichtig für beide Geschlechter. Beeinflusst Knochendichte, kardiovaskuläre Gesundheit, kognitive Funktion und Stimmung. Bei Männern kann ein Überschuss auf Aromataseüberaktivität hinweisen." },
    { param: "Progesteron", unit: "ng/ml", women: "2. Zyklushälfte: >10\nHRT: 2–6", men: "1–2", comment: "Balanciert Östrogeneffekte, wichtig für Schlaf und Stimmung", explanation: "Balanciert Östrogeneffekte. Wichtig für Schlaf, Stimmung und Flüssigkeitshaushalt. Bei Frauen können niedrige Werte zu PMS, unregelmäßigen Zyklen und Unfruchtbarkeit beitragen. Vorstufe zu Cortisol und Aldosteron." },
    { param: "SHBG ⭐", unit: "nmol/l", women: "30–130", men: "20–75", comment: "Reguliert die Bioverfügbarkeit von Sexualhormonen", explanation: "Bindet an Sexualhormone und reguliert deren Bioverfügbarkeit. Hohe Werte reduzieren die Verfügbarkeit freier Hormone. Beeinflusst durch Östrogen (erhöht) und Insulin/Testosteron (verringert)." },
    { param: "Cortisol (morgens)", unit: "µg/dl", women: "16–18", men: "17–18", comment: "Primäres Stresshormon mit diurnaler Rhythmik", explanation: "Primäres Stresshormon mit diurnaler Rhythmik. Beeinflusst Stoffwechsel, Immunfunktion und Blutdruck. Chronische Erhöhung kann zu Insulinresistenz, Immunsuppression und kognitiven Problemen führen." },
    { param: "FSH", unit: "mIU/ml", women: "Follikelphase: 3–15\nOvulation: 4–23\nLutealphase: 1,5–9\nPostmenopause: bis zu 100", men: "bis zu 10", comment: "Unter HRT: 40–60", explanation: "Stimuliert die Follikelentwicklung bei Frauen und die Spermienproduktion bei Männern. Erhöhte Werte bei Frauen können auf verminderte Ovarialreserve oder Menopause hinweisen. Arbeitet mit LH bei der reproduktiven Funktion." },
    { param: "LH", unit: "mIU/ml", women: "Follikelphase: 2,5–13\nOvulation: 9–70\nLutealphase: 1–13\nPostmenopause: 16–55", men: "1,5–10", comment: "FSH/LH-Verhältnis 2:1", explanation: "Löst Eisprung bei Frauen aus und stimuliert die Testosteronproduktion bei Männern. LH:FSH-Verhältnis wichtig für die Diagnose von PCOS und anderen hormonellen Ungleichgewichten. Pulsatile Sekretion beeinflusst Messwerte." },
    { param: "HbA1c ⭐", unit: "%", women: "<5,6", men: "<5,6", comment: "<5,7", explanation: "Spiegelt den durchschnittlichen Blutzucker über die vorangegangenen 2-3 Monate wider. Wichtiger Marker für Diabetesrisiko und -management. Werte zwischen 5,7-6,4% weisen auf Prädiabetes hin; ≥6,5% diagnostisch für Diabetes." }
  ]
};

export default reference;
