// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlrgnuuwgadnkkaapgtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpscmdudXV3Z2FkbmtrYWFwZ3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjgwNTgsImV4cCI6MjA2MTAwNDA1OH0.FPDUIklYRF5qXELsWh0ER7auZ_Ig3nFhxq_qhsKLJQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);